elasticsearch:
  address: localhost
  port:
    http: 9200
    ws: 9300
  bulk:
    size: 5000
    flush: 5000
    concurrent: 3
  index:
  type:

spring:
  datasource:
    url: jdbc:mysql://localhost:3006/business?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username:
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue-name: 

paging:
  pageSize: 5000

threadpool:
  keep-alive-num: 1024