package com.tigerobo.searchhandler.mapper;

import com.tigerobo.searchhandler.entity.EssentialInformation;

public interface EssentialInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essential_information
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    int deleteByPrimaryKey(Integer serialno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essential_information
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    int insert(EssentialInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essential_information
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    int insertSelective(EssentialInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essential_information
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    EssentialInformation selectByPrimaryKey(Integer serialno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essential_information
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    int updateByPrimaryKeySelective(EssentialInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essential_information
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EssentialInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essential_information
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    int updateByPrimaryKey(EssentialInformation record);
}