package com.tigerobo.searchhandler.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ShareholderInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Integer serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Long correlationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.shareholder_name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String shareholderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.shareholder_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String shareholderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.payable_amount
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private BigDecimal payableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.payable_actual_amount
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private BigDecimal payableActualAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.shareholder_credit_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String shareholderCreditType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.shareholder_credit_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String shareholderCreditNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareholder_information.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.serialno
     *
     * @return the value of shareholder_information.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Integer getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.serialno
     *
     * @param serialno the value for shareholder_information.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.correlation_no
     *
     * @return the value of shareholder_information.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Long getCorrelationNo() {
        return correlationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.correlation_no
     *
     * @param correlationNo the value for shareholder_information.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setCorrelationNo(Long correlationNo) {
        this.correlationNo = correlationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.shareholder_name
     *
     * @return the value of shareholder_information.shareholder_name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getShareholderName() {
        return shareholderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.shareholder_name
     *
     * @param shareholderName the value for shareholder_information.shareholder_name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setShareholderName(String shareholderName) {
        this.shareholderName = shareholderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.shareholder_type
     *
     * @return the value of shareholder_information.shareholder_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getShareholderType() {
        return shareholderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.shareholder_type
     *
     * @param shareholderType the value for shareholder_information.shareholder_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setShareholderType(String shareholderType) {
        this.shareholderType = shareholderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.payable_amount
     *
     * @return the value of shareholder_information.payable_amount
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public BigDecimal getPayableAmount() {
        return payableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.payable_amount
     *
     * @param payableAmount the value for shareholder_information.payable_amount
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setPayableAmount(BigDecimal payableAmount) {
        this.payableAmount = payableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.payable_actual_amount
     *
     * @return the value of shareholder_information.payable_actual_amount
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public BigDecimal getPayableActualAmount() {
        return payableActualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.payable_actual_amount
     *
     * @param payableActualAmount the value for shareholder_information.payable_actual_amount
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setPayableActualAmount(BigDecimal payableActualAmount) {
        this.payableActualAmount = payableActualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.shareholder_credit_type
     *
     * @return the value of shareholder_information.shareholder_credit_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getShareholderCreditType() {
        return shareholderCreditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.shareholder_credit_type
     *
     * @param shareholderCreditType the value for shareholder_information.shareholder_credit_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setShareholderCreditType(String shareholderCreditType) {
        this.shareholderCreditType = shareholderCreditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.shareholder_credit_no
     *
     * @return the value of shareholder_information.shareholder_credit_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getShareholderCreditNo() {
        return shareholderCreditNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.shareholder_credit_no
     *
     * @param shareholderCreditNo the value for shareholder_information.shareholder_credit_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setShareholderCreditNo(String shareholderCreditNo) {
        this.shareholderCreditNo = shareholderCreditNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareholder_information.create_time
     *
     * @return the value of shareholder_information.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareholder_information.create_time
     *
     * @param createTime the value for shareholder_information.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}