package searchhandler.entity;

import java.util.Date;

public class EssentialInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Integer serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Long correlationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.registration_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String registrationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.credit_code
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.enterprises_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String enterprisesType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.registered_capital
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Long registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.registered_capital_origin
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String registeredCapitalOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.business_time_start
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date businessTimeStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.registration_authority
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String registrationAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.registration_status
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String registrationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.residence
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String residence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.enterprise_name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.charge_person
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String chargePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.establishment_date
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date establishmentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.business_time_end
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date businessTimeEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.approval_date
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date approvalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.spider_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date spiderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essential_information.business_scope
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String businessScope;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.serialno
     *
     * @return the value of essential_information.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Integer getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.serialno
     *
     * @param serialno the value for essential_information.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.correlation_no
     *
     * @return the value of essential_information.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Long getCorrelationNo() {
        return correlationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.correlation_no
     *
     * @param correlationNo the value for essential_information.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setCorrelationNo(Long correlationNo) {
        this.correlationNo = correlationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.registration_no
     *
     * @return the value of essential_information.registration_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getRegistrationNo() {
        return registrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.registration_no
     *
     * @param registrationNo the value for essential_information.registration_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.credit_code
     *
     * @return the value of essential_information.credit_code
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.credit_code
     *
     * @param creditCode the value for essential_information.credit_code
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.enterprises_type
     *
     * @return the value of essential_information.enterprises_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getEnterprisesType() {
        return enterprisesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.enterprises_type
     *
     * @param enterprisesType the value for essential_information.enterprises_type
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setEnterprisesType(String enterprisesType) {
        this.enterprisesType = enterprisesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.registered_capital
     *
     * @return the value of essential_information.registered_capital
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Long getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.registered_capital
     *
     * @param registeredCapital the value for essential_information.registered_capital
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setRegisteredCapital(Long registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.registered_capital_origin
     *
     * @return the value of essential_information.registered_capital_origin
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getRegisteredCapitalOrigin() {
        return registeredCapitalOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.registered_capital_origin
     *
     * @param registeredCapitalOrigin the value for essential_information.registered_capital_origin
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setRegisteredCapitalOrigin(String registeredCapitalOrigin) {
        this.registeredCapitalOrigin = registeredCapitalOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.business_time_start
     *
     * @return the value of essential_information.business_time_start
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getBusinessTimeStart() {
        return businessTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.business_time_start
     *
     * @param businessTimeStart the value for essential_information.business_time_start
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setBusinessTimeStart(Date businessTimeStart) {
        this.businessTimeStart = businessTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.registration_authority
     *
     * @return the value of essential_information.registration_authority
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getRegistrationAuthority() {
        return registrationAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.registration_authority
     *
     * @param registrationAuthority the value for essential_information.registration_authority
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setRegistrationAuthority(String registrationAuthority) {
        this.registrationAuthority = registrationAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.registration_status
     *
     * @return the value of essential_information.registration_status
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getRegistrationStatus() {
        return registrationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.registration_status
     *
     * @param registrationStatus the value for essential_information.registration_status
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setRegistrationStatus(String registrationStatus) {
        this.registrationStatus = registrationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.residence
     *
     * @return the value of essential_information.residence
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getResidence() {
        return residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.residence
     *
     * @param residence the value for essential_information.residence
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setResidence(String residence) {
        this.residence = residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.enterprise_name
     *
     * @return the value of essential_information.enterprise_name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.enterprise_name
     *
     * @param enterpriseName the value for essential_information.enterprise_name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.charge_person
     *
     * @return the value of essential_information.charge_person
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getChargePerson() {
        return chargePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.charge_person
     *
     * @param chargePerson the value for essential_information.charge_person
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setChargePerson(String chargePerson) {
        this.chargePerson = chargePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.establishment_date
     *
     * @return the value of essential_information.establishment_date
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getEstablishmentDate() {
        return establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.establishment_date
     *
     * @param establishmentDate the value for essential_information.establishment_date
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setEstablishmentDate(Date establishmentDate) {
        this.establishmentDate = establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.business_time_end
     *
     * @return the value of essential_information.business_time_end
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getBusinessTimeEnd() {
        return businessTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.business_time_end
     *
     * @param businessTimeEnd the value for essential_information.business_time_end
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setBusinessTimeEnd(Date businessTimeEnd) {
        this.businessTimeEnd = businessTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.approval_date
     *
     * @return the value of essential_information.approval_date
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.approval_date
     *
     * @param approvalDate the value for essential_information.approval_date
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.create_time
     *
     * @return the value of essential_information.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.create_time
     *
     * @param createTime the value for essential_information.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.spider_time
     *
     * @return the value of essential_information.spider_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getSpiderTime() {
        return spiderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.spider_time
     *
     * @param spiderTime the value for essential_information.spider_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setSpiderTime(Date spiderTime) {
        this.spiderTime = spiderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essential_information.business_scope
     *
     * @return the value of essential_information.business_scope
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essential_information.business_scope
     *
     * @param businessScope the value for essential_information.business_scope
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope;
    }
}