package searchhandler.entity;

import java.util.Date;

public class KeyPersonnel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_personnel.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Integer serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_personnel.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Long correlationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_personnel.name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_personnel.position_md5
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String positionMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_personnel.position_chinese
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private String positionChinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_personnel.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_personnel.serialno
     *
     * @return the value of key_personnel.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Integer getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_personnel.serialno
     *
     * @param serialno the value for key_personnel.serialno
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_personnel.correlation_no
     *
     * @return the value of key_personnel.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Long getCorrelationNo() {
        return correlationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_personnel.correlation_no
     *
     * @param correlationNo the value for key_personnel.correlation_no
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setCorrelationNo(Long correlationNo) {
        this.correlationNo = correlationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_personnel.name
     *
     * @return the value of key_personnel.name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_personnel.name
     *
     * @param name the value for key_personnel.name
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_personnel.position_md5
     *
     * @return the value of key_personnel.position_md5
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getPositionMd5() {
        return positionMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_personnel.position_md5
     *
     * @param positionMd5 the value for key_personnel.position_md5
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setPositionMd5(String positionMd5) {
        this.positionMd5 = positionMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_personnel.position_chinese
     *
     * @return the value of key_personnel.position_chinese
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public String getPositionChinese() {
        return positionChinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_personnel.position_chinese
     *
     * @param positionChinese the value for key_personnel.position_chinese
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setPositionChinese(String positionChinese) {
        this.positionChinese = positionChinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_personnel.create_time
     *
     * @return the value of key_personnel.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_personnel.create_time
     *
     * @param createTime the value for key_personnel.create_time
     *
     * @mbg.generated Tue Dec 11 10:20:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}